cli example
clarify/clarify-go pull request #13
Opened 2022-08-12 11:05 UTC by smyrman

- jsonrpc: allow requests to be logged
- query: add method UnmarshalJSON to filter type
- examples/devdata_cli: new exmaple

2022-08-12 11:07 UTC, smyrman commented on examples/devdata_cli/go.mod
> +replace github.com/clarify/clarify-go v0.2.0 => ../../
Require some changes, so maybe want to bump this to `v0.2.1` after merge of #12.

2022-08-15 11:22 UTC, sarzhann requested changes

2022-08-30 10:36 UTC, smyrman commented
Fixedd & rebased. New Sort method is added in the PR because it's used by the example.

2022-08-30 10:38 UTC, smyrman commented
After merge we should (immediately) release v0.2.2, as it's the version we refer to in go.mod. Cannot refer to v0.2.1 as it doesn't include the Sort method.

2022-09-06 07:39 UTC, sarzhann approved these changes

2022-09-06 12:08 UTC, merged